#!/usr/bin/env python3
import argparse
import sys


from utils import run


parser = argparse.ArgumentParser(
    description="Automatically extract recipes from online websites."
)
parser.add_argument("-l", "--link", help="Input a url link to a recipe")
parser.add_argument(
    "-f",
    "--file",
    help="If you want the output to be in a file, use this flag. Otherwise defaults to console screen.",
    action="store_true",
)
args = parser.parse_args()

# Check if no arguments are passed
if len(sys.argv) == 1:
    parser.print_help()
    sys.exit()

run(args.link, args.file)
